export const partnerFields = [
  { name: "name", label: "Название" },
  { name: "slug", label: "Slug (латиница)" },
  { name: "partnerType", label: "Тип", type: "text" as const },
  { name: "contactName", label: "Контактное лицо" },
  { name: "phone", label: "Телефон" },
  { name: "comment", label: "Комментарий", type: "textarea" as const },
  { name: "udsLink", label: "UDS-ссылка", type: "url" as const },
  { name: "telegramBotLink", label: "Telegram-бот", type: "url" as const },
  { name: "maxBotLink", label: "MAX-бот", type: "url" as const },
  { name: "telegramChannelLink", label: "Telegram-канал", type: "url" as const },
  { name: "maxChannelLink", label: "MAX-канал", type: "url" as const },
  { name: "customHeroTitle", label: "Заголовок hero" },
  { name: "customHeroSubtitle", label: "Подзаголовок hero" },
  { name: "customHeroDescription", label: "Описание hero", type: "textarea" as const },
  { name: "customQrText", label: "Текст QR", type: "textarea" as const },
  { name: "customGiftText", label: "Текст подарка", type: "textarea" as const },
  { name: "isActive", label: "Активен", type: "checkbox" as const },
];
