export const partnerFields = [
  { name: "name", label: "Название гостиницы" },
  { name: "slug", label: "Slug (латиница, для ссылки /gift/slug)" },
  { name: "partnerType", label: "Тип", type: "text" as const },
  { name: "contactName", label: "Контактное лицо (только для админки)" },
  { name: "comment", label: "Комментарий", type: "textarea" as const },
  { name: "udsLink", label: "UDS — только для этой гостиницы" },
  { name: "telegramBotLink", label: "Telegram-бот — только для этой гостиницы" },
  { name: "maxBotLink", label: "MAX-бот — только для этой гостиницы" },
  { name: "customHeroTitle", label: "Заголовок hero (необязательно)" },
  { name: "customHeroSubtitle", label: "Подзаголовок hero" },
  { name: "customHeroDescription", label: "Описание hero", type: "textarea" as const },
  { name: "customGiftText", label: "Текст подарка для печати", type: "textarea" as const },
  { name: "customQrText", label: "Доп. текст на листе печати", type: "textarea" as const },
  { name: "isActive", label: "Активен", type: "checkbox" as const },
];
